### ISSUE TITLE
Sugestão de Readme

### ISSUE THREAD

**Issue by eduardojmatos** [frontendbr/open-source#1]
O @LFeh comentou que faltava um README mais completo pra esse repo.

@frontendbr/admins sugiro colocarmos algo do tipo:

* * *

# Projetos Open-source

Como vimos que na [issue](https://github.com/frontendbr/forum/issues/5) do https://github.com/frontendbr/forum/, temos vários projetos da comunidade que precisam de apoio pra resolver algumas issues ou dar um gás no desenvolvimento, resolvemos adicionar esse repositório pra apoiar esses projetos ou até mesmo criar alguns, conforme sugestões da própria comunidade.

Tínhamos pensado numa [Wiki](https://github.com/frontendbr/forum/wiki/Projetos-open-source), mas acredito que um repo só pra isso pode facilitar a visualização desses projetos :smile: 

## Como sugerir um projeto

Criamos um template pra facilitar a criação da Issue. Assim você pode preencher o template e criar uma issue que a galera consiga entender seu objetivo com o projeto novo.

### 

* * * 

# Template de Issue

Sugiro criarmos um template no seguinte formato

## Nome
Não precisa ser algo muito elaborado, pode ser simples e objetivo.

## Objetivo
Resuma em poucas palavras a motivação de criar o projeto

## Skills necessários
Coloque aqui que tipos de skills serão necessários pra trabalhar nesse projeto. Se um front mais UI, que saiba lidar com interface, UX, ou se um front mais Engineer, que lide com ferramentas de build, task runners, etc.

## Projetos similares
Traga alguns projetos que fazem algo parecido com o que você quer fazer, apenas pra comunidade entender melhor qual o diferencial da sua proposta.

**Comment by LFeh** [comment]
Pra mim está perfeito.

E as labels, como pensa em deixar? Eu fiquei na dúvida! haha

**Comment by fdaciuk** [comment]
Top! Bota pra rodar essa parada ae xD

**Comment by LFeh** [comment]
@eduardojmatos Já coloquei sua sugestão no readme (estava muito tosco, haha), fiz pequenas mudanças.

Vocês sabem como fazer o mesmo esquema do **eventos**, para a issue já abrir com o template?

**Comment by fdaciuk** [comment]
@LFeh é só criar um diretório `.github` na raiz do diretório com um arquivo chamado `issue_template.md`:

https://github.com/frontendbr/eventos/tree/master/.github

:grin:

**Comment by LFeh** [comment]
Facinho =p 

Done!
