### ISSUE TITLE
Contrubuição para o projeto

### ISSUE THREAD

**Issue by RogerioVM** [frontendbr/open-source#100]
Bom dia!

Estou muito interessado em contribuir para o projeto,de qualquer forma, poos quero muito aumentar minhas conexões e acrescentar conhecimento! 
Por favor, podem me dizer como posso contribuir?? Tenho conhecimento de front-end em HTML,CSS,JS e ReactJS e  e o básico de back em NodeJs e PHP.

**Comment by felipefialho** [comment]
O objetivo desse repo é as pessoas postarem projetos que precisam de ajuda. Sugiro que procure algum deles nas issue e se coloque a disposição pra ajudar 🙂
