### ISSUE TITLE
[$$$ por Issue] Outline - Knowledge base

### ISSUE THREAD

**Issue by matbrgz** [frontendbr/open-source#101]
## Nome
Outline - Knowledge base

## Objetivo
Buscamos um profissional/empresa capaz de nos auxiliar a médio e longo prazo (projeto confirmado para 12 meses) no desenvolvimento e/ou aprimoramento de funcionalidades na plataforma open source Outline (https://github.com/outline/outline/).

Nesse primeiro momento vamos trabalhar por issue, para posteriormente trabalhamos com valor por hora. Por isso preciso que envie um orçamento por issue com estimativa de valor e tempo. As issue são:

- Improve Draft https://github.com/outline/outline/issues/1335
- Option to Choose Ordination in a Collection https://github.com/outline/outline/issues/1357
- Add ability to have new lines in tables https://github.com/outline/rich-markdown-editor/issues/206
- Granular Permission https://github.com/outline/outline/issues/1330

Nós imaginamos uma demanda mensal similar a acima pelos próximos 2 meses e no final desse período decidimos se mudamos o formato de contrato. Por conta disso imaginamos um prazo de 1 mês para essas issue acima.

Nosso deadline de escolha do profissional é quarta-feira, para isso estarei online pela plataforma para tirar qualquer dúvida, vale lembrar que discussões técnicas devem ser realizadas através própria issue para que o maintener do projeto participe. 

## Skills necessários
- React
- Mobx
- Node -> Koa (Express a like)
- Postgree

## Projetos similares
- Confluence
- MediaWiki

**Comment by marcel0ll** [comment]
Olá, vocês ainda estão procurando profissional para o desenvolvimento?

**Comment by MatheusRV** [comment]
Yes, estou te chamando no LinkedIn e Facebook

**Comment by alexjosesilva** [comment]
Matheus, de que forma será a sprint: quinzenal ou samanal ?

**Comment by alexjosesilva** [comment]
De que forma possamos evoluir na contratação ?
