### ISSUE TITLE
Ideias de nomes para a "Webschool" da comunidade

### ISSUE THREAD

**Issue by muniz95** [frontendbr/open-source#30]
Deixem suas sugestões de nome abaixo. A mais votada vence e já criamos a org. Caso o nome não esteja disponível, vai o segundo lugar, e assim por diante.

Edit: habemus org [OpenSchool Brasil](https://github.com/openschoolbr)

**Comment by fsoaresjunior** [comment]
devschool

**Comment by NandoKstroNet** [comment]
crowd learning

**Comment by muniz95** [comment]
opencademybr

**Comment by rubenmarcus** [comment]
se o conteúdo envolver só front: frontschool ,mas acho q poderia envolver conteúdo de design, ux/ui tb  e poderia ser openschool

**Comment by kvnol** [comment]
Open School Brasil é lindo.

**Comment by alinebastos** [comment]
Open School é lindo [2]

**Comment by fsoaresjunior** [comment]
realmente acho que open school brasil cairia bem, e claro que o conteúdo tem q ser front, back, infra...

**Comment by NandoKstroNet** [comment]
Open School Brasil +1

**Comment by kvnol** [comment]
![image](https://user-images.githubusercontent.com/3299130/28882841-d34b4e28-7782-11e7-9c7a-c53169620b75.png)

**Comment by rubenmarcus** [comment]
Po da hora que eu contribui pelo menos pela sugestão de nome, quero ajudar como aluno e ou tradutor se formos fazer uma versão em inglês..  Um projeto pessoal meu que tenho muita vontade era de implementar aulas pra crianças de escola públicas, atualmente trabalho voluntário numa ong de São Paulo que tem muitos contatos na área de educação, esse projeto eu queria ver realizado de verdade, mesmo que eu não tenha gabarito pra ser professor, eu iria atrás de no mínimo fazer a ponte entre as pessoas que possam tornar isso viavel.

**Comment by rubenmarcus** [comment]
Uma outra idéia que tive aqui, que baseia na opinião de alguém que falou aqui, as aulas poderiam ser práticas ao extremo, e os alunos poderiam ser avaliados, não só na parte tecnica,mas participativa, por exemplo, exercicios de js, o cara iria ajudar em ideias e projetos opensource que precisasse daquele conteúdo, e as notas do aluno seria um mix, entre participação opensource + avaliação tecnica

não sei nem sei se vai ter esse sistema de avaliação, mas acho que tudo poderia funcionar nesse esquema, até a criação da plataforma do site, provavelmente em NodeJS, que pode virar um tutorial ou curso mesmo, até o desenvolvimento de outras coisas sei lá

**Comment by rubenmarcus** [comment]
Outra forma por exemplo, se tiver cursos de design, poderia ser o aluno que for fazer logo, interfaces ou o que for poderia pegar projetos voluntários, ou projetos open source da comunidade, e ai ja ia fazendo portfolio, a própria galera da mentoria e training center poderia indicar essas pessoas depois em vagas de emprego, ou repassar freelas ( pra quem prefere trabalhar como freelancer e / ou remoto )

**Comment by gabrieldarezzo** [comment]
Curiosidade offtopic
@rubenmarcus  qual o nome da ong? Gostaria de ingressar

**Comment by kvnol** [comment]
@rubenmarcus coloca essa ideia em outra issue, mano. só pra não misturar as ideias.

**Comment by rubenmarcus** [comment]
@gabrieldarezzo  http://www.cemais.org.br , eu fiz a parte de desenvolvimento do site ( Wordpress com tema) e identidade visual + o principal do projeto que é um documentario sobre as atividades da Ong, que eu ainda estou finalizando https://www.facebook.com/maiscatador/   


https://www.youtube.com/watch?v=nlPrZlqI8nw&feature=youtu.be

Como aqui no lance da escola ,eu que sugeri o nome do projeto (Mais Catador) porque a gerente da Ong queria Adote um Catador, e eu achei muito assistencialista

Mas a idéia em curto e medio prazo da ong é passar esse conhecimento sobre meio ambiente e ativismo social nas escolas de São Paulo, principalmente na periferia da Zona Leste,Oeste, Norte e Sul, e ela tem contatos com esse pessoal de ativisimo social e de parcerias publico e privado, e eu poderia comentar sobre o projeto de uma escola Open source voltada para alunos de baixa renda

**Comment by rubenmarcus** [comment]
@kvnol  valeu comentei nessa issue [](https://github.com/frontendbr/open-source/issues/29)

**Comment by muniz95** [comment]
Galera, temos a org criada: [OpenSchool Brasil](https://github.com/openschoolbr)

Criei um [repo](https://github.com/openschoolbr/forum) lá pra iniciarmos as discussões sobre os rumos que tomaremos, seguindo os moldes do fórum daqui do frontendbr.

**Comment by marcosmessias** [comment]
DevCampus

**Comment by kvnol** [comment]
E está saindo do papel! A [identidade visual da Open School Brasil](https://github.com/openschoolbr/forum/issues/3) já está sendo pensada. Quem quiser participar, fique a vontade.

**Comment by kvnol** [comment]
Creio que já daria pra fechar essa issue, tb.
