### ISSUE TITLE
doesangue.me plataforma de doadores de sangue (projeto descontinuado)

### ISSUE THREAD

**Issue by JoseCage** [frontendbr/open-source#37]
## Nome
doesangue.me
_Plataforma online para doadores de sangue_

Github: [Core](https://github.com/doesangueorg/doesangue-core)

## Objetivo
O objetivo principal do projeto é criar um ecossistema (plataforma) onde doadores de sangue, instituições (bancos de sangue, hospitais) se conectam de formas a facilitar o processo de procura de doadores, assim como facilitar aos doadores a encontrar locais e pessoas para doar.
Em primeira instancia o projeto está a ser estruturado apenas para o meu país (Angola :angola:) e se haver interesse em outros países podemos internacionalizar o app ou ainda por ser um projeto _**open source**_ qualquer pessoa pode instalar e criar como um projeto dele..

## Skills necessários
UX/UI, backend (PHP/Laravel).

## Projetos similares
_**Blooder**_  [App](https://play.google.com/store/apps/details?id=br.com.spacebits.blooder) -  [site](http://blooder.com.br/)

**Comment by betofigueiredo** [comment]
Quais seriam as principais funcionalidades? Uma idéia seria adicionar seu tipo sanguíneo e sua localização para ser notificado caso haja necessidade na sua região.

**Comment by JoseCage** [comment]
@betofigueiredo as principais funcionalidades inicialmente (e de forma resumida) são:
  * Encontrar doadores (de um modo geral)
  * Encontrar doadores com compatibilidade sanguinea
  * Encontrar bancos de sangue (verificados)
  * Solicitar doação (__criar campanha__)
  * Notificar aos doadores de sangue (_doadores compatíveis são notificados direitamente_) quando um banco de sangue ou hospital, clinica solicitar doadores..

_Nota que:_ A ideia de avante do que descrevi acima é que esse processo todo de *seleção, confirmação* pudesse ser dentro da plataforma. Podendo assim criar mecanismos de também termos doadores verificados. Daria como *Doadores verificados* aqueles que regularmente doam, os que são sérios no compromisso e enfim..

> Quais seriam as principais funcionalidades? Uma idéia seria adicionar seu tipo sanguíneo e sua localização para ser notificado caso haja necessidade na sua região.

**Comment by felipemartins210** [comment]
Muito bom! vamos começar?

**Comment by JoseCage** [comment]
> Muito bom! vamos começar?

Toda contribuição é bem vinda @felipemartins210 :small_airplane:

**Comment by JoseCage** [comment]
Neste momento tem a [webapp](https://github.com/doesangueorg/doesangue-webapp) com vuejs, a [landingpage](https://github.com/doesangueorg/doesangueorg.github.io) e o [core](https://github.com/doesangueorg/doesangue-core) em desenvolvimento.. Pode ajudar no sentir confortável :smile:

**Comment by jmlavoier** [comment]
Muito boa esta ideia, há quase dois anos atrás iniciamos aqui a desenvolver algo parecido, mas acabamos ficando desmotivados com o tempo, devido a correria. Apoio demais esta ideia, e esporo que consigam cumprir o objetivo. O nosso se chamava [Salve+](https://github.com/SalveMais), mas esta parado.

**Comment by JoseCage** [comment]
Opa @jmlavoier. Lamento terem de parar o projeto. E infelizmente comigo aconteceu o mesmo, principalmente por trabalhar sozinho e precisar investir um pouco mais do que posso de momento.

Escrevi [um post sobre isso](https://medium.com/@JoseCage/chegou-a-hora-do-adeus-doesangue-e-um-recomeço-para-mim-faf11ab27163).

**Comment by JoseCage** [comment]
Já agora, permitam-me fechar a issue tendo em conta que o projeto foi oficialmente [descontinuado](https://medium.com/@JoseCage/chegou-a-hora-do-adeus-doesangue-e-um-recomeço-para-mim-faf11ab27163)...

**Comment by LFeh** [comment]
Que pena cara :(

**Comment by JoseCage** [comment]
> Que pena cara :(

Faz parte. :cry: e no final aprendi demais sobre gestão de projetos (e em especial como gerir um projeto opensource).

**Comment by LFeh** [comment]
@JoseCage Open source pode dar mais trabalho que um projeto normal...

**Comment by JoseCage** [comment]
> Open source pode dar mais trabalho que um projeto normal

É isso que aprendi. Por vezes você precisa estar ai focado e perder horas mexendo com features e tal.

Sobre o regresso, se as coisas correr bem na minha vida pessoal (conseguir emprego, lançar alguns projetos autossustentáveis) irei de certeza trabalhar mais nesse projeto em off e ai se reativar o "open source" é porque já me estabilizei.

**Comment by jmlavoier** [comment]
@JoseCage Poxa vida cara. Mas com certeza foi proveitoso iniciar este projeto. Como você disse, aprendeu muito neste processo. Boa sorte na sua jornada, e quando você voltar, entre em contato comigo, quem sabe não podemos nos unir para fazer esse negocio acontecer.

**Comment by JoseCage** [comment]
> e quando você voltar, entre em contato comigo, quem sabe não podemos nos unir para fazer esse negocio acontecer.

Com certeza que entro em contacto, obrigado.

Se puder me mande um email com teus links (Linkedin, Twitter por exemplo) pra me manter conectado.

:mailbox_with_mail: `josejanuario7@gmail.com`
