### ISSUE TITLE
Novo site do @backend-br

### ISSUE THREAD

**Issue by onhernandes** [frontendbr/open-source#58]
## Site do @backend-br
Temos [nosso site](http://backendbrasil.com.br/), que foi feito em React há um tempo atrás. Agora queremos dar um tapa no layout e mudar, inclusive passar para [hexo.io](hexo.io), porém não temos conhecimento de design pra refazer o layout por isso decidimos pedir ajuda para vocês hehehe.

## Objetivo
O BackEndBrasil funciona como o FrontEndBr, uma organização para reunir os backenders e organizar meetups, eventos e principalmente espalhar a informação para todos.

Nós temos nossa [org aqui](https://github.com/backend-br), no [meetup](https://www.meetup.com/pt-BR/BackEndBr/), [Twitter](https://twitter.com/backendbrasil) e estamos crescendo.

## Skills necessários
Nossa maior dificuldade é com UI, por isso alguém que entenda mais de UI é essencial =] codar nós resolvemos por aqui se precisar hehehe.

**Comment by LFeh** [comment]
Muito bom!

**Comment by LFeh** [comment]
Se liga @kvnol

**Comment by kvnol** [comment]
Isso me lembra que temos que fazer o novo site do FrontendBR ainda, também. :smile:

**Comment by LFeh** [comment]
HHAHAHAHAHAHAHAHAA... mano 😹

**Comment by crisgon** [comment]
Opa, ainda estão precisando de contribuição?

**Comment by onhernandes** [comment]
@crisgon estamos com uma galera pra montar o novo layout mas ajuda é sempre bem-vinda! Temos alguns designers pra montar o layout, me manda teu email pela DM do Twitter(https://twitter.com/BackEndBrasil) que eu te adiciono na conversa.

**Comment by Jhessiny** [comment]
Me adiciona tbm. jhessinymattos@gmail.com

**Comment by onhernandes** [comment]
@Jhessiny ja te coloquei lá.

**Comment by psousaraquel** [comment]
Olá, ainda estão precisando de contribuição?

**Comment by onhernandes** [comment]
Oi @psousaraquel por enquanto não, o site já está no ar, e eu esqueci de fechar a issue. Obrigado!
