### ISSUE TITLE
Projeto colaborativo - Vamos iniciar um projeto e evoluir nosso portfólio?

### ISSUE THREAD

**Issue by juulhao** [frontendbr/open-source#61]
## Objetivo
Pessoal, tudo bem?
Estou a um tempo querendo desenvolver algum projeto, não só para melhorar meu portfólio, mas para por em prática algumas skills que eu vinha estudando. Na comunidade Training Center, puxei uma thread e houve alguns interessados, então me indicaram aqui para divulgar esta proposta e conseguir mais participantes.
Bom vamos lá para a proposta de temas que temos:
- APP/Site para cadastro doações de diversas coisas;
- Plataforma de emprego
- APP para sabermos qual hospital Publico irmos (compartilhar se tem médicos, se está vazio e etc)
- ERP básico de um super mercado ou pequeno negócio
- APP controle Automotivo ( para gerenciar tudo do seu carro)
- APP FIT (pra ficar monstrão ou mostrinha)
 - Temos muitas pessoas que querem aprender tecnologia e não tem condições.(idéia de um colega)
 - Existem serviços como o Skill Share, mas não é acessível para todos.(idéia de um colega)
 - Existe um serviço que acho super legal que é a Cartinha pro Papai Noel, que os Correios fazem. Eu pego uma todo ano inclusive. (idéia de um colega)

## Skills necessários
Todos que se interessarem, seja front-end, UX, Back-end...

Após reunir uma turma interessada, quero discutir como faremos, canal de comunicação, metodologias e etc.
Então fiquem à vontade para opinar!

**Comment by Morette** [comment]
Curti, mas ainda sou iniciante...
Esse projeto seria para todos os niveis?

**Comment by iamrafaela** [comment]
Minha dúvida também é essa.

Enviado do meu iPhone

Em 8 de ago de 2018, à(s) 17:25, Morette <notifications@github.com<mailto:notifications@github.com>> escreveu:


Curti, mas ainda sou iniciante...
Esse projeto seria para todos os niveis?

**Comment by juulhao** [comment]
Tem que caber todos os níveis, seja iniciante ou Sayajin

**Comment by locemarn** [comment]
Massa a ideia de App de apoio para o projeto de Mentoria!
Tenho pouquíssimo tempo livre, mas no que puder ajudar, 'to ae'!!!

**Comment by tgmarinho** [comment]
E um app para monitor ônibus em tempo real, porém, em vez do ônibus ter um mobile lá, o usuário informa onde ele está e envia a sua coordenada para um servidor e o app consome essa informação. Ideia seria fazer PWA com React, e outra turma poderia fazendo com RN, para ter as duas versões e aumentar a quantidade de tecnologia para aprender.

Stack: Javascript, Meteor, React, RN, MongoDB, HTML, CSS.

**Comment by tgmarinho** [comment]
Mentoria é da hora tbm.

De doação quem quiser aprender tem o bora-ajuda do devpleno que é de graça

**Comment by wessleysanttos** [comment]
A ideia do app de top playlist que foi discutido na thread do Training Center eu curti. 
Alias, curti todas essas ideias, qualquer uma que for escolhida eu me proponho a participar.

**Comment by edgarberlinck** [comment]
**Sobre os iniciantes vou deixar minha opinião:**

Creio eu que a ideia deste projeto seria a de **consolidar conhecimento**. Logo se um iniciante quer participar eu não me oponho, isso aqui é Github e qualquer um pode fazer um PR independente do nível de conhecimento.

**Comment by juulhao** [comment]
Exato! @edgarberlinck 
Portanto, a partir de agora deixem aí seus contatos, e escolham um tema. Vou criar uma enquete posteriormente, quando houver quorum

**Comment by edgarberlinck** [comment]
Acho que a melhor forma de entrar em contato é por aqui mesmo @juulhao 

Assuma que quem está aqui vai participar.

**Comment by Alexlopesdev** [comment]
Opa, achei legal todoas ideias, estou aqui para ajudar, ainda não sou profissional gabaritado mais conte comigo para ajudar de qualquer forma...

**Comment by hernanimattos** [comment]
Curti.. gostei do app de doações e hospital.. seria legal dar start ou curar algo que pode realmente fazer diferença na vida das pessoas..

**Comment by AndersonMarquess** [comment]
@edgarberlinck esse do mentoria é legal, não prece ser algo muito complexo então é um bom começo pra saber como seria essa "dinâmica de desenvolvimento".

**Comment by edgarberlinck** [comment]
@AndersonMarquess Eu também gostei dessa idéia e gostaria muito de fazer. Assim, nada impede de ter várias frentes, tudo vai depender da quantidade de gente envolvida.

**Comment by juulhao** [comment]
Bom, pelo que deu pra perceber, a galera ta curtindo essa da mentoria. 
Vamos partir dela então?
Let's bora?
Dando o aval, já crio um repositório, compartilho aqui e definimos um roadmap e branding do mesmo

**Comment by jass2125** [comment]
Eu tenho interesse em participar, codando no back.

**Comment by edgarberlinck** [comment]
@juulhao Tem minha benção.

**Comment by juulhao** [comment]
Boa! fechou então galera!
Qual título dou ao projeto? 
- Projeto APP Mentoria?
- Dash Mentoria
,....

**Comment by edgarberlinck** [comment]
@juulhao Bote Mentoria APP, depois inventamos um nome. Deixa ele vir naturalmente, sou péssimo nomeando as coisas.

**Comment by Alexlopesdev** [comment]
Gente tive uma ideia não sei se flui, que tal criar um aplicativo voltado para pra area inclusão de profissionais de TI em empresas como se fosse "UBER".
 
Os profissionais se cadastram, e irão receber pontuacão por serviço realizado que sera dada pela empresa.

O pagamento do serviço seria feito pelo aplicativo, assim evitando fraude ou calote...

É uma ideia, posso estar falando besteira, mas acho que iria ajudar muitos profissionais que são recem formado, e que
 precisam da 1 oportunidade...

**Comment by edgarberlinck** [comment]
@Alexlopesdev Não acho a ideia ruim, inclusive queriam me contratar para fazer algo parecido.

**Comment by edgarberlinck** [comment]
Sobre a Stack, eu sugiro React + Redux no front. É uma stack bem forte no mercado. Backend podemos fazer em Node.js.

**Comment by juulhao** [comment]
Curti a idéia @Alexlopesdev, acho que cabe até montar um segundo grupo pra desenvolve-la.
@edgarberlinck boa, pode ser,estou fazendo o curso de Nodejs da Rocket seat, gostaria muito de já por em prática

**Comment by hernanimattos** [comment]
Bora..

**Comment by wessleysanttos** [comment]
Boa, bora. 
Eu me proponho a ajudar no back-end, também comecei a estudar NodeJS e gostaria de por em pratica.

**Comment by crisgon** [comment]
Mentorando kkkk

**Comment by edgarberlinck** [comment]
Então demorou. Vai ser legal que estou mentorando uma pessoa em UX e será um bom exercício.

Já fiz um fork do repositório e vou subir um código inicial. Show?

**Comment by Alexlopesdev** [comment]
@juulhao Bora montar este projeto... Vamos fazer algo diferente pra ajudar as pessoas e automaticamente teremos um grande retorno profissional...

**Comment by Alexlopesdev** [comment]
Vamos nos contatar por onde?

**Comment by edgarberlinck** [comment]
@Alexlopesdev Ou por aqui (Prefiro) ou no slack do Training center.

**Comment by Alexlopesdev** [comment]
@edgarberlinck por mim tudo bem...

**Comment by edgarberlinck** [comment]
Fiz um Roadmap e subi um código inicial. Se estiver OK eu faço um PR e vamos dividindo as tarefas.

https://github.com/edgarberlinck/open-source/tree/master/projetos/mentoria-app

**Comment by Alexlopesdev** [comment]
@edgarberlink Acredito que esteja tudo correto...

**Comment by edgarberlinck** [comment]
Abri um PR

**Comment by edgarberlinck** [comment]
Pessoal, agora eu fiz certo hehe. Para facilitar o trabalho eu criei uma company e convidei todos vc`s.

Vamos nos falando por lá.

https://github.com/MentoriaApp/

**Comment by crisgon** [comment]
Opa, posso contribuir com a parte do design. Caso tenham alguma ideia pra logo, posso trabalhar em cima dela.

**Comment by edgarberlinck** [comment]
@crisgon Temos alguns requisitos (Sugestões, na verdade) lá no repositório que postei logo acima. Eu abri uma issue para discutirmos uma das funcionalidades. Você pode sim fazer protótipos e propor logos. Pode usar as issues a vontade.

**Comment by jass2125** [comment]
Eu vi muitas pessoas propondo a stack, mas pelo que vi ainda não foi nada decidido. Acho que o próximo passo poderia ser esse. Fechar  stack que será utilizada.

**Comment by edgarberlinck** [comment]
Até onde ví bateram o martelo com o projeto apenas.

Você tem razão @jass2125. Eu sou meio pra frente e já criei tudo hehehe, mas claro que é apenas uma sugestão (Acredito que alguém tem que começar alguma coisa), estamos abertos.

Então eu convido a todos que deem uma olhada no que fiz até agora e façam PR ou abram uma issue.

**Comment by jass2125** [comment]
Que tal criarmos um channel no slack? A comunicação por lá é mais interativa, ajudaria a definir algumas questões de forma mais rápida.

**Comment by edgarberlinck** [comment]
Temos um canal do Traning Center, como a ideia nasceu lá podemos criar um
Channel ali.

O que vcs fizerem eu topo: grupo no Slack, telegram....

**Comment by hernanimattos** [comment]
Acho legal um cana no slack e um trelinho...

**Comment by taciossbr** [comment]
Canal no slack era uma boa e o trello acho indispensável

**Comment by juulhao** [comment]
Bom pessoal, vamos lá... Vamos criar um channel no Slack, posteriormente quando for mapeado tudo do APP, passamos a dividir as tasks no Trello. 
Quem pode criar o Channel no TC?

**Comment by edgarberlinck** [comment]
Eu não tenho permissão, então quem criar por favor coloque aqui 😁

O GH tem uma funcionalidade de kamban, podemos usar tbm.

De qualquer forma, vou criar um kamban na página do projeto mesmo. Beleza?

**Comment by juulhao** [comment]
Vou criar um Channel, e deixo aqui o link para os que interessarem entrar.

**Comment by edgarberlinck** [comment]
Já criei o board no próprio repositório.

**Comment by juulhao** [comment]
https://join.slack.com/t/mentoriaapp/shared_invite/enQtNDEzMzMzMzM2NDY1LTcyNDgyYTU5MDc4ZDYwMmE0Y2MxZTU3MzhhNDYwNzY1MTFiNWZlYjYwMjMzNzFjZGE4ZjFjYWNiMDY5Zjc0ODY

**Comment by maxdevjs** [comment]
Ola', bela iniciativa...

é possível entrar no projeto para, principalmente, ver como funciona esse tipo de coisa?

**Comment by edgarberlinck** [comment]
@maxdevjs Claro. Entre no slack utilizando o link

>https://join.slack.com/t/mentoriaapp/shared_invite/enQtNDEzMzMzMzM2NDY1LTcyNDgyYTU5MDc4ZDYwMmE0Y2MxZTU3MzhhNDYwNzY1MTFiNWZlYjYwMjMzNzFjZGE4ZjFjYWNiMDY5Zjc0ODY

Lá conversamos.

**Comment by ReneSena** [comment]
Entrei na área recentemente, se eu puder ajudar em algo, estou a disposição. :)

**Comment by edgarberlinck** [comment]
Bem vinda 😀

**Comment by TiagoOliveiraz** [comment]
Olá pessoal. Eu gostaria de contribuir se for possível. Minhas skills são Mysql e PHP nivel intermediario e um pouco de Bootstrap.

**Comment by edgarberlinck** [comment]
@TiagoOliveiraz Entre no slack do projeto, por favor.

**Comment by juulhao** [comment]
Galera, aos interessados, favor entrar no Canal do Slack para maiores informações. Conseguimos quorum e iremos avançar esta semana!
Link: https://join.slack.com/t/mentoriaapp/shared_invite/enQtNDEzMzMzMzM2NDY1LTcyNDgyYTU5MDc4ZDYwMmE0Y2MxZTU3MzhhNDYwNzY1MTFiNWZlYjYwMjMzNzFjZGE4ZjFjYWNiMDY5Zjc0ODY

**Comment by paulo36** [comment]
ola como participar?

**Comment by juulhao** [comment]
@paulo36 leia meu último comment. Fechei esta issue
