### ISSUE TITLE
Logotipo & Interface do @CivitasOrg

### ISSUE THREAD

**Issue by onhernandes** [frontendbr/open-source#65]
## CivitasOrg
Civitas é um projeto totalmente open-source(sem fins lucrativos!) que propõe criar uma aplicação para gerência de comunidades. A ideia é ter um lugar onde as pessoas consigam organizar eventos, ter controle de organizadores/co-organizadores/membros, palestrantes, apoiadores, patrocinadores e etc.

## Objetivo
Não há nenhum aplicativo que supra 100% as necessidades organizacionais das comunidades. Todo mundo desenvolve sua metodologia e usa N ferramentas pra gerenciar isso, e consequentemente, muita gente perde muito tempo com isso. Civitas pode não resolver tudo, e nem ajudar com tudo, mas fará o máximo possível pra melhorar isso.

Se quiser saber melhor, só abrir aqui: [https://github.com/CivitasOrg/about](https://github.com/CivitasOrg/about)

## Skills necessários
- Vontade de ajudar
- UI/Logotipos(é basicamente o que precisamos)

Precisamos de ajuda para bolar o logotipo(pensamos em discutir num fórum sobre qual escolher), desenhar o site principal e o sistema interno.

## Projetos similares
O meetup.com é um projeto parecido, mas o foco dele é apenas em eventos e bem limitado em relação a funcionalidades.

## Contato

Pode ser por aqui, ou pelo e-mail: [civitas@hernandes.io](mailto:civitas@hernandes.io)

**Comment by kvnol** [comment]
Esbocei um logo ontem aqui da firma, mas da pra fazer outro pensando melhor: https://codepen.io/kvnol/pen/KxMeXG

**Comment by onhernandes** [comment]
@kvnol cara, eu não consegui nenhum designer pra ajudar. veio bastante gente conversar sobre o layout e tals, mas não consegui encontrar ninguém pra ajudar com design. eu pensei num logotipo antes e justamente queria usar o mesmo ícone heuheueh. que acha de mantermos esse e futuramente, se necessário, mudarmos? por mim esse ficou ótimo. só precisamos refinar a fonte e o ícone.

o que acha de manter o ícone à direita?

hoje a noite vou chegar em casa e vetorizar esse trem, aí vou subir [aqui](https://github.com/CivitasOrg/brand)

![image](https://user-images.githubusercontent.com/12698656/44997679-86645180-af86-11e8-8449-f8bc6d96f9cd.png)

**Comment by kvnol** [comment]
@onhernandes show, pode ser.

**Comment by onhernandes** [comment]
@kvnol vetorizei, tá aqui: https://drive.google.com/open?id=1IeI8NKFsezxdagVX33M2raUf7I86RE7E

**Comment by onhernandes** [comment]
Atualizei no brand tbm: https://github.com/CivitasOrg/brand

**Comment by onhernandes** [comment]
@kvnol criei um time no Trello pra organizar as coisas por lá. Assim que tiver um layout pronto já da pra começar a desenvolver. Vou ver se essa semana consigo rabiscar alguma coisa e deixar lá pra opinarem

https://trello.com/civitasorg
