### ISSUE TITLE
Birrépi - Projeto open-source para ajudar pessoas com depressão

### ISSUE THREAD

**Issue by hectorgrecco** [frontendbr/open-source#69]
## Nome
Birrépi

## Objetivo
O Birrépi surgiu a partir de uma ideia abstrata postada em uma issue da comunidade @frontendbr com o intuito de ajudar pessoas com depressão ou qualquer outra pessoa que esteja passando por uma situação complicada em sua vida. A premissa é uma plataforma (digamos que também possa ser chamada de rede social) onde a pessoa passando por esse tipo de problema pode postar seu relato, história (de forma anônima ou não) e assim, outros usuários da plataforma podem responder essa mensagem com textos, imagens, músicas de apoio, carinho ou afeto. A ideia nunca foi e nunca será de "substituir" um atendimento psicológico ou psiquiátrico, e sim prover uma certa luz vinda dessa ajuda ao próximo.

## Skills necessários
Front-End (Vue.js, Nuxt.js) e back-end (Node.js, Adonis.js)

## Projetos similares
http://if-me.org

## Comentários
O projeto já tinha sido iniciado com ajuda do fórum de issues da FrontEndBR, mas 90% da equipe sumiu, seja por conta de outras atribulações da vida ou por desinteresse mesmo. Atualmente minha vida está corrida o suficiente pra eu não conseguir desenvolver bastante esse projeto, mas creio que o Hacktober poderia ser a oportunidade perfeita pra finalmente tirar ele do papel. Não foi escrito nem 5% do código necessário pro projeto funcionar, mas já temos a base aqui: https://github.com/birrepi

**Comment by coutinhodiego** [comment]
Olá, sou novo no mundo de desenvolvimento, no git e no open source. Me identifiquei bastante com o projeto. Gostaria de colaborar.
Hoje trabalho com Vue e Nuxt e acho que posso ajudar no projeto.

**Comment by evertonthepaula** [comment]
> Olá, sou novo no mundo de desenvolvimento, no git e no open source. Me identifiquei bastante com o projeto. Gostaria de colaborar.
> Hoje trabalho com Vue e Nuxt e acho que posso ajudar no projeto.

Man eu sou front, pretendendo me tornar full(requisitos da firma ¯\_(ツ)_/¯ ) também to afim de participar, a galera ta meio parada no momento, entra no grupo do slack vamos agitar!  http://bit.ly/SlackBirrepi

**Comment by Gpaula95** [comment]
Boa noite amigo, Sou desenvolvedor, apaixonado por VueJS e Node, tenho experiencia nas duas tecnologias e um grande historico de depressão na familia gostaria de ajudar com esse projeto ! qual seria a melhor forma ?

**Comment by PauloRev** [comment]
Gostaria de ajudar no projeto

**Comment by HenriqueAGT** [comment]
Olá, sou iniciante no mundo da programação, porem gostei muito do tema do projeto, ainda esta em andamento ? como posso iniciar e ajudar de alguma forma.

**Comment by hectorgrecco** [comment]
Fala, @HenriqueAGT. O projeto está parado... começamos a fazer umas coisas mas não foi pra frente... Se quiser tocar, manda ver ;)

**Comment by jass2125** [comment]
A ideia é extremamente interessante, mas me surgiu uma dúvida em relação aos requsitos que devem ser implementados.
