### ISSUE TITLE
Ganhando XP

### ISSUE THREAD

**Issue by ogiansouza** [frontendbr/open-source#73]
## Nome
Ganhando XP

## Objetivo
Estudantes se voluntariando a desenvolver projetos sem fins lucrativos, com auxílio de um pleno ou sênior. Afim de adquirir experiência e montar um portfólio para conseguir seu primeiro emprego ou estágio.

## Skills necessários
- HTML
- CSS
- Vontade de aprender
- Comprometimento

## Projetos similares
http://adoteumbriefing.org/

**Comment by vitumacedu** [comment]
Tenho interesse em potencializar o meu currículo. Vejo que é meio fraco...

**Comment by LFeh** [comment]
Bacana :)

**Comment by ivosoares** [comment]
Muito bom, tenho interesse em participar e a colaborar também !

**Comment by Arieviloo** [comment]
Gostei da idéia,  quero ser um voluntário!!!

**Comment by Rodrigo54** [comment]
Eu tbm quero me voluntariar, quero desenvolver minhas habilidades

**Comment by waldemirflj** [comment]
Quero me voluntária.

**Comment by ogiansouza** [comment]
Bacana pessoal, valeu pelo Feedback!
Quem se interessar entra no slack: https://join.slack.com/t/ganhandoxp/shared_invite/enQtNDY2NTg0ODk2OTgyLTJmMTAzOGYzZjA0MmJhOWNjMzJmZWMwMzYzNGE5Mjk1Mzg4YTFhYzZlOGMzNTBmOTg4NmI0ZmJiZjYzYWMzN2Y

Vamos desenvolver esse projeto!

**Comment by Brubatera** [comment]
Olá! Tenho interesse e acabei de entrar no Slack do grupo. Bora codar!!
