### ISSUE TITLE
Site do BackEndBrasil - Form de pesquisa de Vagas

### ISSUE THREAD

**Issue by onhernandes** [frontendbr/open-source#76]
Oi!

No [site do BackEndBrasil](https://backendbrasil.com.br) estamos com um pequeno bug na área de [vagas](https://backendbrasil.com.br/vagas); quando o usuário aplica um filtro e logo carrega mais `issues` do Github, o filtro não é aplicado para as `issues` vindas da API.

[Abriram uma issue aqui](https://github.com/backend-br/backend-br.github.io/issues/42) relatando esse problema.

Hoje, o filtro todo é bem simples e feito todo no lado do navegador, devido algumas implicações com a API do Github. Ainda vamos trabalhar em uma API nossa para melhorar isso, mas até lá, vamos manter no navegador mesmo.

Se alguém puder e quiser ajudar, agradecemos.

O filtro é feito em JS puro mesmo e temos Babel pra transpilar o código todo. Se quiserem refatorar, fiquem a vontade.

## Skills necessárias
Apenas JS =)

O repositório do site é esse [aqui](http://github.com/backend-br/backend-br.github.io)

Valeu!

**Comment by rafa-acioly** [comment]
seria esse o problema?

![captura de tela 2019-01-03 as 11 07 06](https://user-images.githubusercontent.com/11068059/50639196-bd07a400-0f47-11e9-855e-8d9a009b4b50.png)

**Comment by grippado** [comment]
comentei la na issue, com uma possivel solução que envolve pouco código, e que arruma a priori, a seleção dos estados no filtro!
o problema de não carregar quando clicado, é somente CSS, vou abrir uma PR!

**Comment by onhernandes** [comment]
@rafa-acioly não exatamente, mas pode implicar no filtro.

O filtro é aplicado no navegador, e quando carrega mais issues, o filtro não é aplicado para novas issues. Então tu pode filtrar apenas por SP e quando carregar mais issues, vir algumas de Minas Gerais e exibir ambas, porque o filtro não foi aplicado novamente.

**Comment by Pliavi** [comment]
@onhernandes Estou vendo isso agora, na verdade ele aplica, porém aplica também um filtro pra uma tag "language" que dá 'undefined' que parece que não existe, acabei de só ignorar ela e tudo corre normalmente (um simples if)

Mas esse problema escondia outros, como as vagas se tornam infinitas porque o botão carregar mais não funciona como deveria (por não ter um filtro por trás), ele carrega uma pagina que pode não ter nenhuma vaga do estado, e não carregar nada, e quando chega ao fim, repete a ultima vaga infinitamente enquanto o usuário clicar no botão.

**Comment by onhernandes** [comment]
Problema resolvido, obrigado todo mundo =)
