### ISSUE TITLE
Startup para Venda de Ingressos. 

### ISSUE THREAD

**Issue by IngrdOliveira** [frontendbr/open-source#93]
## Vaib Tickets
É uma plataforma para compra de ingressos de cinema para grupos com desconto. 

## Objetivo
Criar melhor exposição dos Grupos Exibidores, facilitar as formas de pagamento, diminuir os comprovantes em papel, e melhorar a experiencia de compra de ingressos. 
Irei Oferecer Cliff e Vesting aos interessados. 

## Skills necessários
Perdão caso eu me explique mal, não sou muito boa com conhecimento de programação. 
Preciso de 2 FullStacks  (Vou colocar as necessidades, quem souber o nome exato me ajuda aqui)
Preciso que entenda de;
- Compras com cartão / pagamentos / transferências
- Cadastros de dados pessoais
- Segurança online (codigo de barras, keys)
- Adição de contatos (agenda)
- Convites e notificações

## Projetos similares
Ingresso.com
Cine Mobits
Velox tickets

Me chamem por email, prefiro poder explicar melhor o projeto e tudo que esta envolvido. Grata!!

**Comment by nandomoreirame** [comment]
Não ficou claro, o projeto é open-source? cade o repositório?

**Comment by kvnol** [comment]
@IngrdOliveira acho que você postou no repositório errado, não? Na verdade seria o Vagas: https://github.com/frontendbr/vagas

**Comment by IngrdOliveira** [comment]
> Não ficou claro, o projeto é de código aberto? cade o repositório?

Oh man, desculpe eu estou aprendendo a usar esse Github, nunca usei antes.

**Comment by IngrdOliveira** [comment]
> @IngrdOliveira acho que você postou no repositório errado, não? Na verdade seria o Vagas: https://github.com/frontendbr/vagas

Poxa meu consagrado, como que eu faço isso, só copio e ponho vagas? Desculpe estou aprendendo
